In [22]:
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

import numpy as np
from datascience import *

# These lines do some fancy plotting magic.\n",
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [171]:
dataTable = pd.read_csv (r'/Users/nicholaskalinowski/Documents/NBADraftData.csv', encoding= 'unicode_escape')

dataTable['sos'] = 0

#dataTable.drop(dataTable[dataTable['College'] == 'None'].index, inplace = True)

dataTable = dataTable.loc[dataTable["College"] != 'None']
dataTable = dataTable.reset_index()

index1 = 0


for best_player in dataTable.Player:
    best_player_2 = best_player.replace(' ', '-')
    best_player_url = best_player_2 + "-1"
    best_player_url = best_player_url.lower()
    best_player_url = best_player_url.replace('.', '')
    best_player_url = best_player_url.replace("'", '')
    best_player_url = best_player_url.replace('-jr', 'jr')
    best_player_url = best_player_url.replace('-iii', 'iii')
    best_player_url = best_player_url.replace('devyn', 'roy-devyn')
    if best_player_url == 'patrick-williams-1':
        best_player_url = 'patrick-williams-2'
    if best_player_url == 'obi-toppin-1':
        best_player_url = 'obadiah-toppin-1'
    if best_player_url == 'anthony-edwards-1':
        best_player_url = 'anthony-edwards-2'
    if best_player_url == 'nikola-vuevi-1':
        best_player_url = 'nikola-vucevic-1'
    if best_player_url == 'josh-green-1':
        best_player_url = 'josh-green-2'
    if best_player_url == 'xavier-tillman-sr-1':
        best_player_url = 'xavier-tillman-1'
    if best_player_url == 'nick-richards-1':
        best_player_url = 'nick-richards-2'
    if best_player_url == 'reggie-perry-1':
        best_player_url = 'reggie-perry-2'
    if best_player_url == 'ja-morant-1':
        best_player_url = 'temetrius-morant-1'
    if best_player_url == 'kz-okpala-1':
        best_player_url = 'kezie-okpala-1'
    if best_player_url == 'dewan-hernandez-1':
        best_player_url = 'dewan-huell-1'
    if best_player_url == 'mo-bamba-1':
        best_player_url = 'mohamed-bamba-1'
    if best_player_url == 'lonnie-walker-1':
        best_player_url = 'lonnie-walker-2'
    if best_player_url == 'shake-milton-1':
        best_player_url = 'malik-milton-1'
    if best_player_url == 'ray-spalding-1':
        best_player_url = 'raymond-spalding-1'
    if best_player_url == 'bam-adebayo-1':
        best_player_url = 'edrice-adebayo-1'
    if best_player_url == 'kay-felder-1':
        best_player_url = 'kahlil-felder-1'
    if best_player_url == 'larry-nancejr-1':
        best_player_url = 'larry-nance-2'
    if best_player_url == 'tim-hardawayjr-1':
        best_player_url = 'tim-hardaway-jr-1'
    if best_player_url == 'glen-ricejr-1':
        best_player_url = 'glen-rice-jr-1'
    if best_player_url == 'ray-mccallum-1':
        best_player_url = 'ray-mccallum-2'
    if best_player_url == 'thomas-robinson-1':
        best_player_url = 'thomas-robinson-2'
    if best_player_url == 'bernard-james-1':
        best_player_url = 'bernard-james--1'
    if best_player_url == 'kyle-anderson-1':
        best_player_url = 'kyle-anderson-3'
    url = "https://www.sports-reference.com/cbb/players/" + best_player_url + ".html"
    html = urlopen(url)
    soup = BeautifulSoup(html)
    #soup.findAll('tr', limit=2)
    headers = [th.getText() for th in soup.findAll('tr', limit=2)[0].findAll('th')]
    headers = headers[28:]
    #headers
    rows = soup.findAll('tr')[-1:]
    player_stats = [[td.getText() for td in rows[i].findAll('td')]
                    for i in range(len(rows))]
    #print(player_stats[0])
    stats = pd.DataFrame(player_stats, columns=('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'aa', 'sos'))
    stats = stats.drop(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', "w", 'x', 'y', 'z', 'aa'], axis=1)
    dataTable.loc[index1, 'sos'] = stats.sos[0]
    index1 = index1 + 1
    
dataTable

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532

,index,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,...,TRB.1,AST.1,WS,WS/48,BPM,VORP,College SOS,DARKO,LEBRON,sos
0,0,1,1,MIN,Anthony Edwards,Georgia,1.0,72.0,2314.0,1392.0,...,4.7,2.9,0.8,0.017,-2.6,-0.3,8.06,NaN,NaN,8.06
1,1,2,2,GSW,James Wiseman,Memphis,1.0,39.0,836.0,448.0,...,5.8,0.7,0.7,0.042,-5.4,-0.7,5.07,NaN,NaN,5.07
2,3,4,4,CHI,Patrick Williams,Florida State,1.0,71.0,1983.0,655.0,...,4.6,1.4,2.5,0.060,-2.7,-0.3,7.64,NaN,NaN,7.64
3,4,5,5,CLE,Isaac Okoro,Auburn,1.0,67.0,2173.0,646.0,...,3.1,1.9,0.9,0.020,-5.0,-1.6,7.39,NaN,NaN,7.39
4,5,6,6,ATL,Onyeka Okongwu,USC,1.0,50.0,601.0,228.0,...,3.3,0.4,1.9,0.155,-1.3,0.1,7.22,NaN,NaN,7.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,654,55,55,MIA,Semaj Christon,Xavier,1.0,64.0,973.0,183.0,...,1.4,2.0,0.1,0.006,-5.1,-0.8,NaN,NaN,NaN,6.55
529,655,56,56,DEN,Devyn Marble,Iowa,2.0,44.0,457.0,97.0,...,1.6,0.7,-0.3,-0.028,-5.5,-0.4,NaN,NaN,NaN,7.42
530,657,58,58,SAS,Jordan McRae,Tennessee,4.0,123.0,1696.0,846.0,...,1.8,1.4,1.7,0.048,-2.1,0.0,NaN,NaN,NaN,7.30
531,658,59,59,TOR,Xavier Thames,San Diego State,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
532,659,60,60,SAS,Cory Jefferson,Baylor,2.0,58.0,581.0,205.0,...,2.8,0.3,0.9,0.071,-3.3,-0.2,NaN,NaN,NaN,8.32

In [117]:
#  best_player_2 = best_player.replace(' ', '-')
#     best_player_url = best_player_2 + "-1"
#     best_player_url = best_player_url.lower()
#     best_player_url = best_player_url.replace('.', '')
#     best_player_url = best_player_url.replace("'", '')
#     best_player_url = best_player_url.replace('-jr', 'jr')
#     best_player_url = best_player_url.replace('jon-axel', 'jonaxel')
#     best_player_url = best_player_url.replace('boubacar', 'boubecar')
#     if best_player_url == 'remy-martin-1':
#         best_player_url = 'remy-martin-2'
#     if best_player_url == 'obi-toppin-1':
#         best_player_url = 'obadiah-toppin-1'
#     if best_player_url == 'antoine-davis-1':
#         best_player_url = 'antoine-davis-2'
        
#         html = urlopen('https://www.sports-reference.com/cbb/players/nikola-vucevic-1.html')
# soup = BeautifulSoup(html)

# #soup.findAll('tr', limit=2)

# headers = [th.getText() for th in soup.findAll('tr', limit=2)[0].findAll('th')]


# headers = headers[28:]
# headers
# rows = soup.findAll('tr')[-1:]
# player_stats = [[td.getText() for td in rows[i].findAll('td')]
#             for i in range(len(rows))]

# print(player_stats[0])

# stats = pd.DataFrame(player_stats, columns=('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'aa', 'sos'))
# for col in stats.columns:
#     print(col)
# stats = stats.drop(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', "w", 'x', 'y', 'z', 'aa'], axis=1)

IndentationError: unexpected indent (<ipython-input-117-0bcb4231df0a>, line 2)

In [163]:
dataTable2 =  pd.read_csv (r'/Users/nicholaskalinowski/Documents/DARKO.csv', encoding= 'unicode_escape')

dataTable2

,nba_id,Team,Player,DPM,O-DPM,D-DPM,Box DPM,Box O-DPM,Box D-DPM,FGA/100,...,FTA/100,FT%,FTARate%,Usg%,Reb/100,Ast/100,Ast%,Blk/100,Blk%,Tov/100
0,203507,Milwaukee Bucks,Giannis Antetokounmpo,7.24,4.41,2.83,4.77,4.10,0.67,25.671,...,13.222,0.631,0.474,0.314,16.366,6.652,0.238,1.509,0.016,4.619
1,202695,Los Angeles Clippers,Kawhi Leonard,6.13,4.74,1.39,6.96,5.30,1.66,26.809,...,9.944,0.836,0.353,0.312,10.222,6.681,0.244,0.672,0.008,3.721
2,2544,Los Angeles Lakers,LeBron James,6.12,4.75,1.37,5.10,5.33,-0.23,25.593,...,7.409,0.696,0.296,0.301,10.701,11.607,0.422,0.831,0.009,5.126
3,203954,Philadelphia 76ers,Joel Embiid,5.94,3.29,2.65,2.91,2.22,0.69,28.789,...,13.978,0.838,0.530,0.354,16.224,4.314,0.159,2.042,0.021,4.951
4,201142,Brooklyn Nets,Kevin Durant,5.46,5.15,0.31,5.12,4.23,0.89,28.110,...,10.531,0.868,0.367,0.337,11.384,7.761,0.252,1.553,0.018,4.479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1628407,Orlando Magic,Dwayne Bacon,-3.57,-2.15,-1.42,-3.83,-1.83,-2.00,20.761,...,5.684,0.809,0.276,0.218,6.043,2.964,0.097,0.263,0.003,1.559
496,1629647,Oklahoma City Thunder,Darius Bazley,-3.63,-1.93,-1.69,-4.00,-1.58,-2.42,21.150,...,6.283,0.718,0.314,0.234,10.269,3.302,0.123,0.644,0.007,3.427
497,1630197,Oklahoma City Thunder,Aleksej Pokusevski,-3.98,-2.96,-1.03,-3.83,-3.00,-0.83,18.211,...,2.514,0.727,0.157,0.197,8.880,4.508,0.149,1.488,0.016,3.700
498,1630177,Oklahoma City Thunder,Theo Maledon,-4.34,-2.71,-1.63,-4.22,-2.42,-1.80,19.338,...,4.899,0.762,0.278,0.217,5.536,6.433,0.203,0.354,0.004,3.682
499,2617,Miami Heat,Udonis Haslem,-4.83,-4.79,-0.05,-3.74,-3.91,0.17,10.563,...,1.406,0.543,0.107,0.116,12.459,1.408,0.046,0.824,0.010,1.226

In [167]:
mergedSet = pd.merge(dataTable, dataTable2, on="Player")

mergedSet

,index,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,...,FTA/100,FT%_y,FTARate%,Usg%,Reb/100,Ast/100,Ast%,Blk/100,Blk%,Tov/100
0,0,1,1,MIN,Anthony Edwards,Georgia,1.0,72.0,2314.0,1392.0,...,6.630,0.782,0.288,0.265,7.730,4.975,0.165,0.786,0.010,3.317
1,1,2,2,GSW,James Wiseman,Memphis,1.0,39.0,836.0,448.0,...,5.301,0.640,0.245,0.244,13.061,1.491,0.059,1.993,0.021,3.068
2,3,4,4,CHI,Patrick Williams,Florida State,1.0,71.0,1983.0,655.0,...,3.637,0.741,0.260,0.175,8.075,2.818,0.089,1.017,0.011,2.062
3,4,5,5,CLE,Isaac Okoro,Auburn,1.0,67.0,2173.0,646.0,...,4.548,0.753,0.320,0.181,5.600,3.545,0.120,0.518,0.006,2.349
4,5,6,6,ATL,Onyeka Okongwu,USC,1.0,50.0,601.0,228.0,...,4.924,0.665,0.349,0.141,13.814,1.246,0.035,2.569,0.031,2.051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,632,33,33,CLE,Joe Harris,Virginia,7.0,400.0,10178.0,4426.0,...,1.326,0.775,0.103,0.136,5.570,2.291,0.059,0.230,0.002,1.318
276,637,38,38,DET,Spencer Dinwiddie,Colorado,7.0,320.0,8226.0,4123.0,...,9.298,0.763,0.435,0.240,5.946,9.222,0.280,0.378,0.004,3.979
277,638,39,39,PHI,Jerami Grant,Syracuse,7.0,508.0,12954.0,5425.0,...,10.244,0.784,0.392,0.306,6.516,4.298,0.150,1.432,0.017,2.985
278,644,45,45,CHH,Dwight Powell,Stanford,7.0,429.0,7922.0,3209.0,...,6.322,0.742,0.619,0.135,12.975,3.516,0.091,1.489,0.017,1.858
279,645,46,46,WAS,Jordan Clarkson,Missouri,7.0,521.0,14050.0,7950.0,...,4.008,0.863,0.168,0.270,6.472,3.978,0.129,0.302,0.003,2.743

In [172]:
mergedSet.to_csv('/Users/nicholaskalinowski/Documents/DataWithDARKO.csv')

In [175]:
dataTable3 =  pd.read_csv (r'/Users/nicholaskalinowski/Documents/LEBRON data.csv', encoding= 'unicode_escape')

mergedSet2 = pd.merge(dataTable, dataTable3, on="Player")

mergedSet2.to_csv('/Users/nicholaskalinowski/Documents/DataWithLEBRON.csv')